### ISSUE TITLE
hi is this for softethervpn api ?

### ISSUE THREAD

**Issue by Dankvpn** [hoppler/SoftEtherApi#1]
if yes can i contact u on skype or discord ?

**Comment by hoppler** [comment]
Yes, this is for SoftEther VPN Server. I dont have skype or discord. Ask your question here

**Comment by Dankvpn** [comment]
thx so much for reply me i wan just ask you i have website for vpn and i wan to use softether vpn can u do some work for me and i pay u for ur work ?


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by hoppler** [comment]
Hi,

you can describe which features youre missing in the current code and then we can discuss it.

**Comment by hoppler** [comment]
im closing it because of inactivity
