### ISSUE TITLE
How to set option for group ??

### ISSUE THREAD

**Issue by abolfazl-biria** [hoppler/SoftEtherApi#10]
I can't set option for group 😕

**Comment by hoppler** [comment]
group has no "option" field
![image](https://user-images.githubusercontent.com/2553766/123593384-bb548980-d7ee-11eb-89e9-ff03dbddf7ec.png)

**Comment by abolfazl-biria** [comment]
I know this
 But I do not know how to set options for groups in c # code (softetherApi)

**Comment by abolfazl-biria** [comment]
I how to can set security policy for group using softetherApi

**Comment by hoppler** [comment]
now i know what you want. security-policy setting is not implemented. as i have no use case im my project, there will not be an implementation in the future by me.

Adding it is still not that complicated, you need to add a PolicyModel with its field and extend the SetGroup method to use it.

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/03d67fd5b1550b421bd511d0d4782facd3bca9bb/src/Cedar/Admin.c#L14353-L14372

and

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/ce6ea9f781d8ffb078477477b6f55e9dc89a4f41/src/Cedar/Protocol.c#L5328-L5389

**Comment by abolfazl-biria** [comment]
Thanks 😊
