### ISSUE TITLE
Authentication failed 

### ISSUE THREAD

**Issue by lukastrkan** [hoppler/SoftEtherApi#3]
Hi, I am unable to connect, app alway crash with this error. 
![image](https://user-images.githubusercontent.com/19746629/44410456-b3673c00-a564-11e8-89fe-e93004405a66.png)

Here is my code:
```
            var ip = "xxx";
            ushort port = 5555; //one of the ports out of the Listener List (443, 992, 1194, 5555)
            var pw = "xx";

            using (var softEther = new SoftEther(ip, port))
            {
                var connectResult = softEther.Connect();
                if (!connectResult.Valid())
                {
                    Console.WriteLine(connectResult.Error);
                    return;
                }

                var authResult = softEther.Authenticate(pw);
                if (!authResult.Valid())
                {
                    Console.WriteLine(authResult.Error);
                    return;
                }

                var user = softEther.HubApi.CreateUser("VPN", username, password);
                Console.WriteLine(user.Valid() ? "Success" : user.Error.ToString());
            }
```

Any suggestions? Thanks

**Comment by hoppler** [comment]
Im guessing its something about tls/ssl. The exception is thrown when the ssl connection could not be established. 

I guess you have to play with those lines as i cannot replicate your system.

https://github.com/hoppler/SoftEtherApi/blob/ee6bb57c2192d32898f54fe0d4fdb3e2da714b4c/SoftEtherApi/SoftEther.cs#L27-L28

**Comment by chipitsine** [comment]
Can you provide wireshark dump? I guess it is something regarding ssl3 settings

**Comment by lukastrkan** [comment]
I hope that I did it right 😄 
[wtf.zip](https://github.com/hoppler/SoftEtherApi/files/2306989/wtf.zip)

**Comment by lukastrkan** [comment]
Well, It looks like that its problem with my pc. When I run it on Linux (writen in .net core 2.1) it started working as expected. But still I want to find the problem 😅

**Comment by lukastrkan** [comment]
Well, I have just fixed it. Everything I have to do is change Encryption algorithm from RC4-MD5 to AES128-SHA.
But still, thanks guys 😄

**Comment by hoppler** [comment]
the reason for this: windows does not allow rc4 for ssl connections and after changing it you now use aes128 which is valid
