### ISSUE TITLE
show connected sessions?

### ISSUE THREAD

**Issue by ashah7** [hoppler/SoftEtherApi#4]
Hi - 
anything that shows connected sessions?

**Comment by hoppler** [comment]
Yes, you can find the Apis in the Api folder

https://github.com/hoppler/SoftEtherApi/tree/master/SoftEtherApi/Api

https://github.com/hoppler/SoftEtherApi/blob/99ee422678781bc2827ac09c10e895f6da739c7b/SoftEtherApi/Api/SoftEtherHub.cs#L271-L281

**Comment by ashah7** [comment]
thanks
is this also a correct way to get the sessions?

`var hubnow = softEther.HubApi.GetSessionList("hubname");` 
` hubnow.ElementAt(0).UserName`

**Comment by hoppler** [comment]
yes

**Comment by hoppler** [comment]
Hi,

its missing currently. Maybe ill add it in the next days. The following code is missing:

```c#
public SoftEtherList<HubIpList> GetIpList(string hubName)
{
	var requestData = new SoftEtherParameterCollection
	{
		{"HubName", hubName}
	};

	var rawData = _softEther.CallMethod("EnumIpTable", requestData);
	return HubIpList.DeserializeMany(rawData);
}
```
```c#
public class HubIpList : BaseSoftEtherModel<HubIpList>
{
	public DateTime CreatedTime;
	public bool DhcpAllocated;
	public string HubName;
	public IPAddress Ip;
	public byte[] Ip_ipv6_array;
	public bool Ip_ipv6_bool;
	public uint Ip_ipv6_scope_id;
	public bool IpV6;
	public byte[] IpV6_ipv6_array;
	public bool IpV6_ipv6_bool;
	public uint IpV6_ipv6_scope_id;
	public uint Key;
	public string RemoteHostname;
	public uint RemoteItem;
	public string SessionName;
	public DateTime UpdatedTime;
}
```

**Comment by ashah7** [comment]
please do this would be very useful.....good project softether is a great vpn...

**Comment by hoppler** [comment]
please take a look at the link and tell me what other functions should be added so i dont have to update the package multiple times

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/63c01ba736a4cd4ab75ba82ab34a3fdcf235a115/src/Cedar/Admin.c#L336-L476

**Comment by ashah7** [comment]
currently you have all the functions that I will be using in the build the only one I can think of that is missing is ipv4 DHCP address of the client.  If you could build with this that would work for me...
thanks

**Comment by hoppler** [comment]
the required methods are added in https://github.com/hoppler/SoftEtherApi/commit/14011f963400629150952f63633862859102fa39

The nuget package is updated to and is currently beeing indexed by nuget.

You can either use:
https://github.com/hoppler/SoftEtherApi/blob/e386e14d0fd98f54558bbb3a643f1190accfae9c/SoftEtherApi/Api/SoftEtherHub.cs#L309

or if the ip is provided always provided by dhcp per
https://github.com/hoppler/SoftEtherApi/blob/e386e14d0fd98f54558bbb3a643f1190accfae9c/SoftEtherApi/Api/SoftEtherHub.cs#L343

**Comment by hoppler** [comment]
vpncmd does the filtering in code but still requests the whole iptable.

you can filter the code by using linq:
```c#
// The session you need is in sessionList[1]
var sessionList = softEther.HubApi.GetSessionList(hubName);
var ipEntry= softEther.HubApi.GetIpAddressList(hubName).FirstOrDefault(m => m.SessionName == sessionList[1].Name);
```
