### ISSUE TITLE
[Feature Request] Client API

### ISSUE THREAD

**Issue by M0n7y5** [hoppler/SoftEtherApi#5]
Hello,
can you implement client API? So you can communicate with client on localhost like vpncmd?

**Comment by hoppler** [comment]
Hi,

as i dont use vpncmd, please make an example of what command is missing for you.

------ Originalnachricht ------
Von: "M0n7y5" <notifications@github.com<mailto:notifications@github.com>>
An: "hoppler/SoftEtherApi" <SoftEtherApi@noreply.github.com<mailto:SoftEtherApi@noreply.github.com>>
Cc: "Subscribed" <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Gesendet: 10.04.2019 13:43:49
Betreff: [hoppler/SoftEtherApi] [Feature Request] Client API (#5)


Hello,
can you implement client API? So you can communicate with client on localhost like vpncmd?

**Comment by M0n7y5** [comment]
I am missing all commands for client API

**Comment by M0n7y5** [comment]
[Reference ](https://www.softether.org/4-docs/1-manual/6._Command_Line_Management_Utility_Manual/6.5_VPN_Client_Management_Command_Reference)

**Comment by hoppler** [comment]
SoftEther seems to not have a external api for the client-stuff youd like to control. The commands available per remote are the following. (vpncmd and remoteApi are different architectures)

https://github.com/SoftEtherVPN/SoftEtherVPN/blob/63c01ba736a4cd4ab75ba82ab34a3fdcf235a115/src/Cedar/Admin.c#L336-L476

**Comment by M0n7y5** [comment]
Yeah, but RPC declarations in Admin.c are only for server API 
I found this: https://github.com/SoftEtherVPN/SoftEtherVPN/blob/63c01ba736a4cd4ab75ba82ab34a3fdcf235a115/src/Cedar/Client.h#L450

**Comment by hoppler** [comment]
The difference is, the serverRpc serializes the data for me so i can just call the command and know what to excpect where as the clientRpc doest not have such a feature but implements its "serialization" in every client function. To implement such a feature i would have to port problably nearly all of client.c and helper functions into c#.

You can always open a ticken at the softether repo and ask if there is a clientRpc which is callable like the serverRpc and if not there is nothing i can do for you as im not using the clientRpc Api at all.
