### ISSUE TITLE
Help listing users.

### ISSUE THREAD

**Issue by rampso** [hoppler/SoftEtherApi#8]
Hi I've been trying to figure out how to list users for ages right now I would just be happy if could get it to return them. The add user function works flawlessly but I just don't think I'm using the userlist properly at all.

            var ip = "xx";
            ushort port = xx; 
            var pw = "xx";

            using (var softEther = new SoftEther(ip, port))
            {
                var connectResult = softEther.Connect();
                var authResult = softEther.Authenticate(pw);

                var userlist = softEther.HubApi.GetUserList("HUB");

                Console.WriteLine(userlist);

that just returns the following.. I honestly very new to coding and would really appreciate a working example of this function to help me understand it. Hoping somebody is active here.

SoftEtherApi.Containers.SoftEtherList`1[SoftEtherApi.SoftEtherModel.HubUserList]

**Comment by hoppler** [comment]
userlist is a list. you cant console.writeline() a list without further code. as this is no softether issue ill close it

**Comment by rampso** [comment]
Was just about to update that I finally figured it out, I always seem to get something to work right as I ask for help.
