### ISSUE TITLE
Change User Password and make User (de)active

### ISSUE THREAD

**Issue by seppy87** [hoppler/SoftEtherApi#9]
Hallo,
I am making a Programm which makes single login Softether User. 
If Username not known it creates a new User with random generated PW. it sends the PW via TLS to my Server Programme which sneds it to the User.
If the User logs off from my Server. it sends a REST Request to deactivate the User.
If the User logs in again the Server sends a REST Request to create user. The SoftEther Programme recognizes it has the user and reactivates it with a new Password and sends the new PW to the Server.

How do I activate User and deactivate one?
and how do I change the password?
I found a HashedKey. but which hash it uses for Passwords?

**Comment by hoppler** [comment]
Seems like you didnt look properly:

https://github.com/hoppler/SoftEtherApi/blob/e386e14d0fd98f54558bbb3a643f1190accfae9c/SoftEtherApi/Api/SoftEtherHub.cs#L578

You cant activeate/deactivate a user, but you can set an expiration date which disables userlogin
https://github.com/hoppler/SoftEtherApi/blob/e386e14d0fd98f54558bbb3a643f1190accfae9c/SoftEtherApi/Api/SoftEtherHub.cs#L571
